### PR TITLE
Update FileProvider to use androidX

### PR DESCRIPTION
**Pull request by erodrigues-dev**
After update to AndroidX, build is broken, this change refactor to work again

### CODE REVIEW

**Comment by pwlin** [comment]
Hi @erodrigues-dev Thanks for this PR. If I merge this PR, does the plugin still works on older Android (5,6,7,8 etc) devices?

**Comment by erodrigues-dev** [comment]
It won't, because the class namespace has been changed to androidx, sorry

**Comment by pwlin** [comment]
Thanks for explanation. We need to find a way to make this backward compatible otherwise a lot of users with older Android devices will not be able to use this plugin anymore.

**Comment by drewwynne0** [comment]
@erodrigues-dev I suspect you are looking for cordova-plugin-androidx-adapter - i was running v1.1.0 but since updating to v1.1.1 all is working again

**Comment by erodrigues-dev** [comment]
> @erodrigues-dev I suspect you are looking for cordova-plugin-androidx-adapter - i was running v1.1.0 but since updating to v1.1.1 all is working again

I tested this lib but it didn't work, the only way I found was to fork the project and installed it at npm pointing to my fork

**Comment by erodrigues-dev** [comment]
> Thanks for explanation. We need to find a way to make this backward compatible otherwise a lot of users with older Android devices will not be able to use this plugin anymore.

I understand, I don't know how to help you with this, my project broke after this update and I needed a solution quickly. So I forked the project and corrected the compilation error, and changed the dependency of the project to use my fork.

**Comment by pwlin** [comment]
It's all right, thanks for your PR anyway. I still have adding Android X in my todo list for this plugin.

**Comment by erodrigues-dev** [comment]
> It's all right, thanks for your PR anyway. I still have adding Android X support for this plugin in my todo list.

I think the best way is to update the plugin for androidX.
Users will continue to use your plugin in old projects, using a previous release.
You could make that clear in the project readme.

**Comment by ucsbricks** [comment]
@erodrigues-dev I am sorry, but I don’t believe your suggested approach is practical. One app binary has to support all Android versions. There is no way to convince a customer they should publish to different apps, one for older devices and another one for newer devices.

**Comment by erodrigues-dev** [comment]
> @erodrigues-dev I am sorry, but I don’t believe your suggested approach is practical. One app binary has to support all Android versions. There is no way to convince a customer they should publish to different apps, one for older devices and another one for newer devices.

This would be the perfect scenario, I hope you can

**Comment by StefanVanStaden** [comment]
@erodrigues-dev I am going to point the npm package to this fork as well until it is merged. Driving me nuts changing the package name after every build during the development cycle.

**Comment by erodrigues-dev** [comment]
> @erodrigues-dev I am going to point the npm package to this fork as well until it is merged. Driving me nuts changing the package name after every build during the development cycle.

Feel free my friend. Follow the command

``` sh
npm i cordova-plugin-file-opener2@erodrigues-dev/cordova-plugin-file-opener2
```

**Comment by WuglyakBolgoink** [comment]
@erodrigues-dev  / @pwlin 

any updates??

I think supporting androidX should be finished in a new major version and ppl must upgrade plugin. 

"androidx.appcompat:appcompat:X.Y.Z" replace the old v4 support...

**Comment by erodrigues-dev** [comment]
Hi, use [jetifier npm package](https://www.npmjs.com/package/jetifier)
