### ISSUE TITLE
Use FileProvider for all Android versions, including Android 5 and earlier

### ISSUE THREAD

**Issue by imgx64** [pwlin/cordova-plugin-file-opener2#174]
Looking at the [code](https://github.com/pwlin/cordova-plugin-file-opener2/blob/021a0ac73db220fba16286d06fb8d6e8c0ce8345/src/android/io/github/pwlin/cordova/plugins/fileopener2/FileOpener2.java#L107), it seems that FileProvider is only used on Android API >= 23 (Marshmallow). This prevents opening files in private app directories (such as /data/data/app-id/files/*) in other apps on Android 5 and earlier.

I modified the plugin to always use FileProvider and it worked correctly on Android 4.1 (The earliest version supported by Cordova). And as a bonus, `android.permission.WRITE_EXTERNAL_STORAGE` is no longer required.

Is there a reason it's this way? Can it be changed?

**Comment by boboldehampsink** [comment]
Can you submit a PR for that? I'd like to test it.

**Comment by skar3** [comment]
thank you, i have problems opening files on Android < 6.0, a new versione of the plugin will be released?

**Comment by gutosoares** [comment]
I'm also facing the problem @skar3 reported.
Here is the error in the build process:

```
Error: /home/mlearn/Documentos/mLearn/app/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/home/mlearn/Documentos/mLearn/app/platforms/android/src/io/github/pwlin/cordova/plugins/fileopener2/FileOpener2.java:110: error: cannot find symbol
					if (Build.VERSION.SDK_INT < Build.VERSION_CODES.N) {
					                                               ^
  symbol:   variable N
  location: class VERSION_CODES
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

Can you help?

**Comment by imgx64** [comment]
@gutosoares Install the latest Android SDK and upgrade your app to use the latest `cordova-android` version.

**Comment by imgx64** [comment]
Fixed by #176.
